CC = gcc
CFLAGS = -g

proj3 : proj3.o
	$(GCC) $(CFLAGS) -c proj3.o -o proj3

proj2 : Proj2.o
	$(GCC) $(CFLAGS) -c Proj2.o -o proj2

proj3.o : proj3.c
	$(GCC) $(CFLAGS) -c proj3.c

Proj2.o : Proj2.c
	$(GCC) $(CFLAGS) -c Proj2.c